### ISSUE TITLE
Questions, not a bug

### ISSUE THREAD

**Issue by bradparks** [Raudaschl/historical_crypto_trade_simulator#1]
Hey... Cool idea... I'm interested in the same concept, but lazier than you it seems, lol!

Some quick questions:
- Does this do trading for you? If so, where's this configured? It sounds like it might do that from your "Customize" step in the README
- Where do your initial investments go? I don't see a step saying "put what you've got in this csv file"

Thanks for the work. I got here from your medium article, fyi

**Comment by Raudaschl** [comment]
Hey @bradparks ,

Thanks for the support. Happy to answer some questions:
1. This does not trade for you, but certainly the idea crossed my mind. Its primarily just to historically simulate a strategy, but there is not reason you could not reconfigure with a cryptomarket api like bittrex or bitfinex.
2. You enter your initial investments into the bitCoinOrders array in trader.py for example if I bought bitcoin on the 2017-06-28 I would put the buy price, coin type and number of coins bought into a format like this:

bitCoinOrders.append({"coin": "btc", "buyPrice": 2600, "coins": 0.0702, "date": "2017-06-28"})

Let me know if that answers your question.

**Comment by bradparks** [comment]
ahh... cool... I get it now... thanks! That clears it up for sure
