### ISSUE TITLE
download.py: not using filename in the coinTypes dict

### ISSUE THREAD

**Issue by bastiaan85** [Raudaschl/historical_crypto_trade_simulator#2]
You enter a filename per coin type in the `coinTypes` dict. However, when you actually save to a file, you use a hardcoded filename of `str(CoinType)+".csv"`. Why not use the filenames in the dict? Eg

```
for coin_type, filename in coin_types.items():
    # other code
    prices.to_csv(filename, index=False)
```

Note I'm also using PEP8 name conventions instead of camelCase that's meant for class names.

**Comment by Raudaschl** [comment]
@bastiaan85 thanks for the heads up. I have made the update
